name: mlops-exaple-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # or any version compatible with your setup
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip install -r requirements.txt
      - name: Train model
        run: python model.py
      - name: Publish and send report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
