name: mlops-exaple-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # or your desired version
      - name: Install dependencies in virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install ci-cd-ml
      - name: Train model
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip  
          pip install dvc[cml]  
      - name: Publish and send report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          echo "\n## Model Performance" >> report.md
          echo "Model performance metrics are on the plot below." >> report.md
          cml-publish model_results.png --md >> report.md
          cml-send-comment report.md
